"""fix city id type

Revision ID: 22bfc8cf0ae1
Revises: 3f484f1a0baf
Create Date: 2026-10-02 20:38:07.841182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22bfc8cf0ae1'
down_revision: Union[str, Sequence[str], None] = '3f484f1a0baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_venue_name_location'), table_name='venues')
    op.create_index('uq_venue_name_location', 'venues', ['name', 'location'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_venue_name_location', table_name='venues')
    op.create_index(op.f('uq_venue_name_location'), 'venues', [sa.literal_column('lower(name::text)'), sa.literal_column('lower(location::text)')], unique=True)
    # ### end Alembic commands ###
