"""add event category

Revision ID: 930050da154b
Revises: 53226af8e909
Create Date: 2026-09-18 13:45:34.516161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '930050da154b'
down_revision: Union[str, Sequence[str], None] = '53226af8e909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('events', sa.Column('event_type', sa.String(length=50), nullable=False))
    op.add_column('events', sa.Column('category_id', sa.Integer(), nullable=False))
    
    op.create_foreign_key(
    'fk_events_category_id',
    'events',
    'categories',
    ['category_id'],
    ['id'],
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    
    op.drop_constraint(
    'fk_events_category_id',
    'events',
    type_='foreignkey',
)
    op.drop_column('events', 'category_id')
    op.drop_column('events', 'event_type')
    op.drop_table('categories')
    # ### end Alembic commands ###
