"""make venue uniqueness case insensitive

Revision ID: e02b1d4c0cff
Revises: e111bb001be6
Create Date: 2026-09-23 22:04:00.820603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e02b1d4c0cff'
down_revision: Union[str, Sequence[str], None] = 'e111bb001be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_venue_name_location'), 'venues', type_='unique')
    op.create_index('uq_venue_name_location', 'venues', [sa.literal_column('lower(name)'), sa.literal_column('lower(location)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_venue_name_location', table_name='venues')
    op.create_unique_constraint(op.f('uq_venue_name_location'), 'venues', ['name', 'location'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
