"""add venue name location unique constraint

Revision ID: e111bb001be6
Revises: 48a77ef76b56
Create Date: 2026-09-23 18:45:36.603179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e111bb001be6'
down_revision: Union[str, Sequence[str], None] = '48a77ef76b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_venue_name_location', 'venues', ['name', 'location'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_venue_name_location', 'venues', type_='unique')
    # ### end Alembic commands ###
